.TH ROX 1 "2002" "Thomas Leonard" ""
.SH NAME
ROX-Filer \- a simple graphical file manager
.SH SYNOPSIS

.B rox
[\fBOPTION\fP]... [FILE]... 
.SH DESCRIPTION
.PP
ROX-Filer is a simple and easy to use graphical file manager for X11, the windowing system used on Unix and Unix-like operating systems.

.PP
It is also the core component of the ROX Desktop:
http://rox.sourceforge.net

.PP
Invoking
.B rox
opens each directory or file listed, or the current working directory if no arguments are given.
.SH COMMAND-LINE OPTIONS
.PP
 
.TP
\fB-b\fP, \fB--bottom=PANEL\fP
open PANEL as a bottom-edge panel.
      
.TP
\fB-c\fP, \fB--client-id=ID\fP
used for session management.
      
.TP
\fB-d\fP, \fB--dir=DIR\fP
open DIR as directory (not as an application, even if it looks like one).
      
.TP
\fB-D\fP, \fB--close=DIR\fP
close DIR and all its subdirectories.
      
.TP
\fB-h\fP, \fB--help\fP
display help about the various options.
      
.TP
\fB-l\fP, \fB--left=PANEL\fP
open PANEL as a left-edge panel.
      
.TP
\fB-m\fP, \fB--mime-type=FILE\fP
print MIME type of FILE and exit.
      
.TP
\fB-n\fP, \fB--new\fP
start a new filer, even if one already seems to be running. This also prevents the filer from forking (running in the background), which is useful for debugging.
      
.TP
\fB-o\fP, \fB--override\fP
override window manager control of panels.
      
.TP
\fB-p\fP, \fB--pinboard=PIN\fP
use pinboard PIN as the pinboard.
      
.TP
\fB-r\fP, \fB--right=PANEL\fP
open PANEL as a right-edge panel.
      
.TP
\fB-R\fP, \fB--RPC\fP
read and invoke SOAP RPC from standard input (see the manual).
      
.TP
\fB-s\fP, \fB--show=FILE\fP
open a directory showing FILE.
      
.TP
\fB-t\fP, \fB--top=PANEL\fP
open PANEL as a top-edge panel.
      
.TP
\fB-u\fP, \fB--user\fP
show user name in each window.
      
.TP
\fB-v\fP, \fB--version\fP
display the version information and exit.
      
.TP
\fB-x\fP, \fB--examine=FILE\fP
FILE has changed; re-examine it.
       
.SH NOTES
.PP
The main documentation for ROX-Filer is available by choosing Show ROX-Filer Help from the popup menu, or by clicking on the i toolbar icon.
.SH LICENSE
.PP
Copyright (C) 2002 Thomas Leonard.

.PP
You may redistribute copies of ROX-Filer under the terms of the GNU General Public License.
.SH BUGS
.PP
Report bugs to <tal197@users.sourceforge.net>.
.SH AUTHORS
.PP
ROX-Filer was created by Thomas Leonard, with help from:

.PP
Christopher Arndt,
Jens Askengren,
Liav Asseraf,
Wilbert Berendsen,
Francesco Bochicchio,
Andrzej Borsuk,
Richard Boulton,
Simon Britnell,
Arnaud Calvo,
Andrew Clover,
Fabien Coutant,
Couderc Damien,
Andreas Dehmel,
Dmitry Elfimov,
Mattias Engdegard,
Andrew Flegg,
Olivier Fourdan,
Eric Gillespie,
Thierry Godefroy,
Alex Holden,
Jasper Huijsmans,
Bernard Jungen,
James Kermode,
Jim Knoble,
Krzysztof Krzyzaniak,
Vincent Ledda,
Vincent Lefevre,
Victor Liu See-le,
Anders Lundmark,
Jose Romildo Malaquias,
Denis Manente,
Andras Mohari,
Christiansen Merel,
Jimmy Olgeni,
Andy Piper,
Marcelo Ramos,
Michel Alexandre Salim,
Chris Sawer,
Taras,
Simon Truss,
Jan Wagemakers,
Stephen Watson,
Andre Wyrwa,
Diego Zamboni

.PP
and many others; the Changes file contains more detailed information!
